DeclareModule xyView_Common
  EnableExplicit

  ;{ MACROS
  Macro AppendElement(_list)
    LastElement(_list) : AddElement(_list)
  EndMacro
  ;}

  ;{ STRUCTURES / PROTOTYPES
  
  ;}

  ;{ CONSTANTS
  #PROJECT_NAME = "xyView"
  ;}

  ;{ GLOBALS
  
  ;}

  ;{ DECLARES
  Declare.s UUID()
  Declare FatalError(message.s)
  ;}
EndDeclareModule

;- INCLUDES: DECLARES
;{
XIncludeFile "xyViewD.pb"
;} END DECLARES

;- INCLUDES: MODULES
;{
;} END MODULES

Module xyView_Common
  EnableExplicit

  ;{ MACROS
  
  ;}

  ;{ STRUCTURES / PROTOTYPES
  
  ;}

  ;{ CONSTANTS
  
  ;}

  ;{ GLOBALS
  
  ;}

  ;{ DECLARES
  
  ;}

  ;{ PROCEDURES
  ;- PRIVATE
  ;- PUBLIC
  Procedure.s UUID()
    Define uuid.s, i.i

    For i = 1 to 16
      uuid + RSet(Hex(Random(255) & $FF), 2, "0")
    Next

    ProcedureReturn uuid
  EndProcedure

  Procedure FatalError(message.s)
    MessageRequester(#PROJECT_NAME, message, #PB_MessageRequester_Ok | #PB_MessageRequester_Error)
    End
  EndProcedure
  ;}
EndModule
; IDE Options
; Module generated by PBOrganizer